### ISSUE TITLE
A100 support

### ISSUE THREAD

**Issue by lscat11** [microsoft/nnfusion#344]
Hi! I have tried running `nnfusion` on A100. I notice the A100 did not support the `nvprof` which is used in `src/tools/nnfusion/kernel_db/profile.py`. I was wondering how to generate the kernel db correctly for A100, e.g., using `ncu`.

**Comment by xysmlx** [comment]
Hi, thank you for your attention. 

You may change the nvprof command in [this script](https://github.com/microsoft/nnfusion/blob/master/src/tools/nnfusion/kernel_db/profile.py#L171) to the ncu version. This function returns the device name and the kernel execution time. The sm_80 information is also needed in the [Makefile](https://github.com/microsoft/nnfusion/blob/master/src/tools/nnfusion/kernel_db/profile.py#L18).

BTW, to let nnfusion generate available model code on A100, the A100's sm_80 information (-gencode arch=compute_80,code=sm_80) is needed in the [compilation flag](https://github.com/microsoft/nnfusion/blob/master/src/nnfusion/engine/pass/codegen/cuda_codegen_pass.cpp#L1250).
