### ISSUE TITLE
[BUG] model compile error cuz shape disagree

### ISSUE THREAD

**Issue by lixeon** [microsoft/nnfusion#362]
**🐛 Bug**
`[ERROR] 2021-11-22T11:17:00z src/nnfusion/util/errors.hpp 169   While validating op 'MatMul_1' of type 'Dot':
Check failed: 'arg0_shape[axis_index_arg0].compatible(arg1_shape[axis_index_arg1])' at /root/nnfusion/thirdparty/ngraph/src/nnfusion/core/operators/op_define/dot.cpp:103:
Paired axes (axis 1 from arg0, axis 0 from arg1) do not have same length (arg0 shape: {0,0}, arg1 shape: {256,256}, reduction axes count: 1transA: 0, transB: 0).
terminate called after throwing an instance of 'nnfusion::errors::CheckError'
  what():  While validating op 'MatMul_1' of type 'Dot':
Check failed: 'arg0_shape[axis_index_arg0].compatible(arg1_shape[axis_index_arg1])' at /root/nnfusion/thirdparty/ngraph/src/nnfusion/core/operators/op_define/dot.cpp:103:
Paired axes (axis 1 from arg0, axis 0 from arg1) do not have same length (arg0 shape: {0,0}, arg1 shape: {256,256}, reduction axes count: 1transA: 0, transB: 0).
Aborted (core dumped)`

**To Reproduce**
1.  step by README

**Expected behavior**
run it normally

**Additional context**
I use 4 hosts , the first is Geforce GTX TITAN X - 470.74 ,  and the second is 4x M40 - 440.33.01 , both reproduce the same error. However, A100 which divided into 7 GPU instance by MIG  it is works , but the main_test seems wrong,  many 00000 and the Iteration time very weird.
And last , the single Geforce RTX 2080 seems run  correctly. 

```
root@A100-docker:~/frozen_models/frozen_lstm_l8s8h256_bs1/cuda_codegen# cat main_test.log
Result_2261_0: 
0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00  .. (size = 256, ends with 0.000000e+00);
Result_2261_0: 
0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00  .. (size = 256, ends with 0.000000e+00);
Result_2261_0: 
0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00  .. (size = 256, ends with 0.000000e+00);
Result_2261_0: 
0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00  .. (size = 256, ends with 0.000000e+00);
Result_2261_0: 
0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00 0.000000e+00  .. (size = 256, ends with 0.000000e+00);
Iteration time 7.533248 ms
Iteration time 7.573344 ms
Iteration time 7.404128 ms
Iteration time 5.714272 ms
......
Iteration time 7.588544 ms
Summary: [min, max, mean] = [3.913216, 7.595328, 8.787529] ms
```

 
```
root@RTX2080-docker:~/nnfusion_rt/cuda_codegen# ./main_test 
Result_2261_0: 
8.921492e-03 1.182088e-02 8.937406e-03 7.932204e-03 1.574194e-02 3.844390e-03 -1.505094e-02 -1.112035e-02 5.026608e-03 -8.032205e-03  .. (size = 256, ends with 1.357487e-02);
Result_2261_0: 
8.921492e-03 1.182088e-02 8.937406e-03 7.932204e-03 1.574194e-02 3.844390e-03 -1.505094e-02 -1.112035e-02 5.026608e-03 -8.032205e-03  .. (size = 256, ends with 1.357487e-02);
Result_2261_0: 
8.921492e-03 1.182088e-02 8.937406e-03 7.932204e-03 1.574194e-02 3.844390e-03 -1.505094e-02 -1.112035e-02 5.026608e-03 -8.032205e-03  .. (size = 256, ends with 1.357487e-02);
Result_2261_0: 
8.921492e-03 1.182088e-02 8.937406e-03 7.932204e-03 1.574194e-02 3.844390e-03 -1.505094e-02 -1.112035e-02 5.026608e-03 -8.032205e-03  .. (size = 256, ends with 1.357487e-02);
Result_2261_0: 
8.921492e-03 1.182088e-02 8.937406e-03 7.932204e-03 1.574194e-02 3.844390e-03 -1.505094e-02 -1.112035e-02 5.026608e-03 -8.032205e-03  .. (size = 256, ends with 1.357487e-02);
Iteration time 2.319136 ms
....
Iteration time 1.676960 ms
Iteration time 1.703520 ms
Iteration time 1.675136 ms
Summary: [min, max, mean] = [1.660608, 2.361664, 2.224415] ms
```

**Comment by xysmlx** [comment]
Hi, thank you for your attention. The [nvcc compilation flags](https://github.com/microsoft/nnfusion/blob/master/src/nnfusion/engine/pass/codegen/cuda_codegen_pass.cpp#L1250) of NNFusion only contain Pascal (sm60, sm61) and Volta/Turing (sm70, sm75). You may add the corresponding sm information of Titan X, M40 and A100 in the compilation flag in [cuda_codegen_pass](https://github.com/microsoft/nnfusion/blob/master/src/nnfusion/engine/pass/codegen/cuda_codegen_pass.cpp#L1250) and [profiler](https://github.com/microsoft/nnfusion/blob/master/src/nnfusion/engine/profiler/cuda_runtime.cpp#L490) [cupti_profiler](https://github.com/microsoft/nnfusion/blob/master/src/nnfusion/engine/profiler/cuda_runtime.cpp#L1028). The profiler is used for constant_folding.

**Comment by lixeon** [comment]
> 

It works~
Thank you again for your amazing work.
