### ISSUE TITLE
hi , when i use your plugin it appears:cudaScaleRunner.cpp (119) - Cuda Error in execute: 700,

### ISSUE THREAD

**Issue by scuizhibin** [microsoft/nnfusion#405]
**🐛 Bug**

**To Reproduce**
1. 
2. 
3. 

**Expected behavior**

**Additional context**

**Comment by xysmlx** [comment]
Hi, could you provide more details about the error, e.g., how to reproduce this problem? And what is the plugin? Thank you.

**Comment by scuizhibin** [comment]
When&nbsp;I&nbsp;use&nbsp;the&nbsp;Tensorrt&nbsp;-DCNV2&nbsp;plugin,cudaScaleRunner.cpp&nbsp;(119)&nbsp;-&nbsp;Cuda&nbsp;Error&nbsp;in&nbsp;execute:&nbsp;700&nbsp;(an&nbsp;illegal&nbsp;memoryaccess&nbsp;was&nbsp;encountered)&nbsp;appears。&nbsp;


---Original---
From: &quot;Lingxiao ***@***.***&gt;
Date: Wed, Apr 6, 2022 23:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [microsoft/nnfusion] hi , when i use your plugin itappears:cudaScaleRunner.cpp (119) - Cuda Error in execute: 700, (Issue #405)




 
Hi, could you provide more details about the error, e.g., how to reproduce this problem? And what is the plugin? Thank you.
 
&mdash;

**Comment by xysmlx** [comment]
Hi, it seems to be the problems of TensorRT or the plugin. You may ask questions in the TensorRT repo or the plugin repo. Thank you.
